### ISSUE TITLE
Call for Participants

### ISSUE THREAD

**Issue by drjwbaker** [LibraryCarpentry/city-november-2015#5]
If you are interested in finding out more or in bringing a group to [Library Carpentry](http://librarycarpentry.github.io/city-november-2015/), let us know!

Note that places will be allocated at the discretion of the organisers (we are nice folks so you can trust us to be fair!)

**Comment by libchris** [comment]
Yes please I'm interested to know more - think there are some others from Cambridge interested too

**Comment by drjwbaker** [comment]
Excellent! Celine and I had an exchange [earlier in the month](https://twitter.com/j_w_baker/statuses/594113461518479360?tw_i=594113461518479360&tw_e=permalink&tw_p=archive) so I'll put down a Cambridge cohort.

**Comment by cjclib** [comment]
Yes, I'm definitely still interested and Chris & I can see if there's any other Cambridge people who'd like to join our cohort :)

**Comment by drjwbaker** [comment]
Excellent! Keep me updated by I'll assume 3ish from Cambridge.

**Comment by ClareP** [comment]
I'm really interested in coming but it may be dependant on the success of a funding application for my travel expenses.  I also can't say right now whether or not I'll be able to form a group although I am going to try to scrape a few southerners together (from Brighton and surrounding area). Would you still consider participants who come alone? Thanks, Clare (University of Sussex).

**Comment by jennpb** [comment]
I'm definitely interested. May be able to wrangle a few colleagues from Wellcome Library.

**Comment by ClareP** [comment]
Ok so I've got one definite (me), one almost certain and two possibles from the South East now :)

**Comment by drjwbaker** [comment]
@ClareP : excellent! Official booking will go out sometime over the summer so there is time to pull some folks together. In the meantime, I'll earmark 4

@jennpb: As above really. Shall I put the Wellcome down for a few provisional places?

**Comment by jennpb** [comment]
@drjwbaker Two from Wellcome for certain.

**Comment by jennpb** [comment]
and hello @ClareP! I know your sister (at least I think she's your sister!). Happy days.

**Comment by ClareP** [comment]
@drjwbaker Thanks!

@jennpb Hello! Yes you probably do know my sister, she's famous in library land :D I'm crossing my fingers she'll be one our Southern crew!

**Comment by JimTim81** [comment]
Yes, I would be interested - and I'm trying to get together a City Uni Library crowd, too!

**Comment by JimTim81** [comment]
6 so far...

**Comment by drjwbaker** [comment]
Hi Tim. You should have a chat with [Ernesto Priego](https://twitter.com/ernestopriego) as we have a batch of places set aside of citylis folks (hosts privilege and all that).

**Comment by cjclib** [comment]
Hi James - I've got quite a lot of potential interest from Cambridge. Even though they're not all definite, I've got another 5 possibles apart from me and Chris so it might be worth pencilling in a slightly bigger Cambridge cohort than the 3 we originally agreed (I doubt everyone who has expressed an interest will end up being able to come but it might end up being 4 or 5 once people have looked into the logistics)

**Comment by drjwbaker** [comment]
Great! Looking at getting out a formal signup thing soonish, but this is helpful for initial planning.

**Comment by drjwbaker** [comment]
@JimTim81 @cjclib @libchris @jennpb : could you please either post you email addresses here or send it to me at james.baker@bl.uk. Following on from your expression of interest in Library Carpentry, I'm am nearly ready to confirm bookings and hope to send an email round next week with some final details so you (and your organisation) can make an informed decision about whether or not to attend.
Thanks!

**Comment by jennpb** [comment]
@drjwbaker I can be reached at j.phillips-bacher@wellcome.ac.uk.

**Comment by drjwbaker** [comment]
Thanks @jennpb! To confirm for those listed on my note from 2 days ago, this means that I have your email addresses and will be in touch this week.

**Comment by JimTim81** [comment]
I think we had ten interested in doing it from here at city. I'll ask around again this week and see if interest is still there.
On 5 Jul 2015 09:49, James Baker notifications@github.com wrote:Thanks @jennpb! To confirm for those listed on my note from 2 days ago, this means that I have your email addresses and will be in touch this week.

**Comment by drjwbaker** [comment]
Call closed.
